version: '3'
services:
  application:
    container_name: parking_lot_app
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POSTGRES_URL=jdbc:postgresql://parking_lot_postgres:5432/postgres
    depends_on:
      - postgres
      - redis
    links:
      - redis
    restart: on-failure
  postgres:
    container_name: parking_lot_postgres
    image: postgres
    env_file:
      - .env
    hostname: parking_lot_postgres
    restart: on-failure
