package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ParkingLotProductionDockerBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ParkingLotProductionDockerBuild")) {
    triggers {
        add {
            schedule {
                schedulingPolicy = cron {
                    hours = "1"
                    dayOfMonth = "29"
                    month = "3"
                    year = "2022"
                }
                branchFilter = "+:/refs/tags/promo"
                triggerBuild = always()
            }
        }
    }
}
